### ISSUE TITLE
Wrong category

### ISSUE THREAD

**Issue by balamurugan15** [balamurugan15/Notifix#3]
App puts the notification in the wrong category

**Comment by Raamakrishnan** [comment]
1. App TV Time not being categorised (https://github.com/balamurugan15/Notifix/issues/9)
2. Todoist remainder is categorised as Promotions
3. Two very similar Event notifications from Sastra Hub are categorised into 2 different categories.
<img src="https://user-images.githubusercontent.com/9772489/38160360-ff213908-34d9-11e8-96f5-6f439b853aa9.png" height="500" />

**Comment by balamurugan15** [comment]
Should be solved in the latest version 0.8b (Hopefully)

**Comment by Raamakrishnan** [comment]
"ISS detector" app's notification for next sighting of ISS is classified as "Promotions". "News" might be a better category.

**Comment by Raamakrishnan** [comment]
The "now playing" notification of Wync music is being categorised as "Promotions". Should be left uncategorised.

**Comment by Raamakrishnan** [comment]
Still experiencing the same issue with TV time and Todoist in 0.8b

**Comment by balamurugan15** [comment]
Wync music is wync app issue man.

For TV Time  & Todoist, try clearing app data for Notifix and log in again in the app (Notifix) & reboot.  That'll clear old categories. Even then if the prob exists, lemme know!

**Comment by balamurugan15** [comment]
Fixed an internal category issue. Do try the latest v0.9. Hopefully fixes uncategorized issues,
